# Generated by Django 5.0.4 on 2024-04-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mastodonhubClubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=120)),
                ('PresidentName', models.TextField()),
                ('TreasurerName', models.TextField()),
                ('AdvisorName', models.TextField()),
                ('Email', models.TextField()),
                ('ImageUrl', models.URLField()),
                ('Category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='mastodonhubDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=120)),
                ('Description', models.TextField()),
                ('ImageUrl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='mastodonhubEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=120)),
                ('Description', models.TextField()),
                ('Location', models.CharField(max_length=120)),
                ('Date', models.DateField()),
                ('StartTime', models.TimeField()),
                ('EndTime', models.TimeField()),
                ('ImageUrl', models.URLField()),
                ('Category', models.CharField(max_length=50)),
            ],
        ),
    ]
