INSERT INTO `movies`.`type` (`type_id`,`type`) VALUES (1,'TV Show');
INSERT INTO `movies`.`type` (`type_id`,`type`) VALUES (2,'Movie');
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (1,'Blood & Water',NULL,1,'South Africa',2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (2,'Ganglands','Julien Leclercq',1,NULL,2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (3,'Jailbirds New Orleans',NULL,1,NULL,2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (4,'Kota Factory',NULL,1,'India',2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (5,'Midnight Mass','Mike Flanagan',1,NULL,2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (6,'My Little Pony: A New Generation','Robert Cullen, José Luis Ucha',2,NULL,2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (7,'Sankofa','Haile Gerima',2,'United States, Ghana, Burkina Faso, United Kingdom, Germany, Ethiopia',1993);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (8,'The Great British Baking Show','Andy Devonshire',1,'United Kingdom',2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (9,'The Starling','Theodore Melfi',2,'United States',2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (10,'Vendetta: Truth, Lies and The Mafia',NULL,1,NULL,2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (11,'Bangkok Breaking','Kongkiat Komesiri',1,NULL,2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (12,'Je Suis Karl','Christian Schwochow',2,'Germany, Czech Republic',2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (13,'Confessions of an Invisible Girl','Bruno Garotti',2,NULL,2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (14,'Crime Stories: India Detectives',NULL,1,NULL,2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (15,'Dear White People',NULL,1,'United States',2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (16,'Europe''s Most Dangerous Man: Otto Skorzeny in Spain','Pedro de Echave García, Pablo Azorín Williams',2,NULL,2020);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (17,'Falsa identidad',NULL,1,'Mexico',2020);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (18,'Intrusion','Adam Salky',2,NULL,2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (19,'Jaguar',NULL,1,NULL,2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (20,'Monsters Inside: The 24 Faces of Billy Milligan','Olivier Megaton',1,NULL,2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (21,'Resurrection: Ertugrul',NULL,1,'Turkey',2018);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (22,'Avvai Shanmughi','K.S. Ravikumar',2,NULL,1996);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (23,'Go! Go! Cory Carson: Chrissy Takes the Wheel','Alex Woo, Stanley Moore',2,NULL,2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (24,'Jeans','S. Shankar',2,'India',1998);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (25,'Love on the Spectrum',NULL,1,'Australia',2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (26,'Minsara Kanavu','Rajiv Menon',2,NULL,1997);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (27,'Grown Ups','Dennis Dugan',2,'United States',2010);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (28,'Dark Skies','Scott Stewart',2,'United States',2013);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (29,'Paranoia','Robert Luketic',2,'United States, India, France',2013);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (30,'Ankahi Kahaniya','Ashwiny Iyer Tiwari, Abhishek Chaubey, Saket Chaudhary',2,NULL,2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (31,'Chicago Party Aunt',NULL,1,NULL,2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (32,'Sex Education',NULL,1,'United Kingdom',2020);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (33,'Squid Game',NULL,1,NULL,2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (34,'Tayo and Little Wizards',NULL,1,NULL,2020);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (35,'The Father Who Moves Mountains','Daniel Sandu',2,NULL,2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (36,'The Stronghold','Cédric Jimenez',2,NULL,2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (37,'Angry Birds',NULL,1,'Finland',2018);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (38,'Birth of the Dragon','George Nolfi',2,'China, Canada, United States',2017);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (39,'Chhota Bheem',NULL,1,'India',2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (40,'He-Man and the Masters of the Universe',NULL,1,'United States',2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (41,'Jaws','Steven Spielberg',2,'United States',1975);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (42,'Jaws 2','Jeannot Szwarc',2,'United States',1978);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (43,'Jaws 3','Joe Alves',2,'United States',1983);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (44,'Jaws: The Revenge','Joseph Sargent',2,'United States',1987);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (45,'My Heroes Were Cowboys','Tyler Greco',2,NULL,2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (46,'Safe House','Daniel Espinosa',2,'South Africa, United States, Japan',2012);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (47,'The Smart Money Woman','Bunmi Ajakaiye',1,NULL,2020);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (48,'Training Day','Antoine Fuqua',2,'United States',2001);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (49,'Castle and Castle',NULL,1,'Nigeria',2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (50,'Dharmakshetra',NULL,1,'India',2014);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (51,'InuYasha the 2 2: The Castle Beyond the Looking Glass','Toshiya Shinohara',2,'Japan',2002);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (52,'InuYasha the 2 3: Swords of an Honorable Ruler','Toshiya Shinohara',2,'Japan',2003);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (53,'InuYasha the 2 4: Fire on the Mystic Island','Toshiya Shinohara',2,'Japan',2004);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (54,'InuYasha the 2: Affections Touching Across Time','Toshiya Shinohara',2,'Japan',2001);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (55,'Nailed It',NULL,1,'United States',2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (56,'Naruto Shippuden the 2: Blood Prison','Masahiko Murata',2,'Japan',2011);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (57,'Naruto Shippûden the 2: Bonds','Hajime Kamegaki',2,'Japan',2008);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (58,'Naruto Shippûden the 2: The Will of Fire','Masahiko Murata',2,'Japan',2009);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (59,'Naruto Shippuden: The 2','Hajime Kamegaki',2,'Japan',2007);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (60,'Naruto Shippuden: The 2: The Lost Tower','Masahiko Murata',2,'Japan',2010);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (61,'Naruto the 2 2: Legend of the Stone of Gelel','Hirotsugu Kawasaki',2,'Japan',2005);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (62,'Naruto the 2 3: Guardians of the Crescent Moon Kingdom','Toshiyuki Tsuru',2,'Japan',2006);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (63,'Naruto the 2: Ninja Clash in the Land of Snow','Tensai Okamura',2,'Japan',2004);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (64,'Nightbooks','David Yarovesky',2,NULL,2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (65,'Numberblocks',NULL,1,'United Kingdom',2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (66,'Raja Rasoi Aur Anya Kahaniyan',NULL,1,'India',2014);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (67,'Saved by the Bell',NULL,1,'United States',1994);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (68,'Schumacher','Hanns-Bruno Kammertöns, Vanessa Nöcker, Michael Wech',2,NULL,2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (69,'Stories by Rabindranath Tagore',NULL,1,'India',2015);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (70,'Too Hot To Handle: Latino',NULL,1,NULL,2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (71,'A StoryBots Space Adventure','David A. Vargas',2,NULL,2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (72,'Jack Whitehall: Travels with My Father',NULL,1,'United Kingdom',2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (73,'King of Boys','Kemi Adetiba',2,'Nigeria',2018);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (74,'The World''s Most Amazing Vacation Rentals',NULL,1,NULL,2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (75,'You vs. Wild: Out Cold','Ben Simms',2,NULL,2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (76,'Yowamushi Pedal',NULL,1,'Japan',2013);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (77,'Little Singham - Black Shadow','Prakash Satam',2,NULL,2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (78,'Tughlaq Durbar','Delhiprasad Deenadayalan',2,NULL,2020);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (79,'Tughlaq Durbar (Telugu)','Delhiprasad Deenadayalan',2,NULL,2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (80,'Firedrake the Silver Dragon','Tomer Eshed',2,NULL,2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (81,'Kate','Cedric Nicolas-Troyan',2,'United States',2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (82,'Lucifer',NULL,1,'United States',2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (83,'Metal Shop Masters',NULL,1,NULL,2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (84,'Omo Ghetto: the Saga','JJC Skillz, Funke Akindele',2,'Nigeria',2020);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (85,'Pokémon Master Journeys: The Series',NULL,1,NULL,2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (86,'Prey','Thomas Sieben',2,NULL,2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (87,'Titipo Titipo',NULL,1,NULL,2019);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (88,'Blood Brothers: Malcolm X & Muhammad Ali','Marcus Clarke',2,NULL,2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (89,'Mighty Raju',NULL,1,NULL,2017);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (90,'Paradise Hills','Alice Waddington',2,'Spain, United States',2019);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (91,'The Women and the Murderer','Mona Achache, Patricia Tourancheau',2,'France',2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (92,'Into the Night',NULL,1,'Belgium',2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (93,'JJ+E','Alexis Almström',2,NULL,2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (94,'Show Dogs','Raja Gosnell',2,'United Kingdom, United States',2018);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (95,'The Circle',NULL,1,'United States, United Kingdom',2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (96,'If I Leave Here Tomorrow: A Film About Lynyrd Skynyrd','Stephen Kijak',2,'United States',2018);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (97,'Kid Cosmic',NULL,1,'United States',2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (98,'Octonauts: Above & Beyond',NULL,1,'United Kingdom',2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (99,'On the Verge',NULL,1,'France, United States',2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (100,'Tobot Galaxy Detectives',NULL,1,NULL,2019);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (101,'Untold: Breaking Point','Chapman Way, Maclain Way',2,'United States',2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (102,'Countdown: Inspiration4 Mission to Space','Jason Hehir',1,NULL,2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (103,'Shadow Parties','Yemi Amodu',2,NULL,2020);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (104,'Tayo the Little Bus',NULL,1,'South Korea',2016);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (105,'Angamaly Diaries','Lijo Jose Pellissery',2,'India',2017);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (106,'Bunk''d',NULL,1,'United States',2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (107,'A Champion Heart','David de Vos',2,'United States',2018);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (108,'Dive Club',NULL,1,'Australia',2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (109,'La casa de papel',NULL,1,'Spain',2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (110,'Money Heist: From Tokyo to Berlin','Luis Alfaro, Javier Gómez Santander',1,NULL,2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (111,'Sharkdog',NULL,1,'United States, Singapore',2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (112,'Worth','Sara Colangelo',2,NULL,2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (113,'Shadow Parties 2','Yemi Amodu',2,NULL,2020);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (114,'Anjaam','Rahul Rawail',2,'India',1994);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (115,'Bright Star','Jane Campion',2,'United Kingdom, Australia, France',2009);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (116,'Dhanak','Nagesh Kukunoor',2,'India',2015);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (117,'Final Account','Luke Holland',2,'United Kingdom, United States',2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (118,'Gurgaon','Shanker Raman',2,'India',2017);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (119,'Here and There','JP Habac',2,NULL,2020);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (120,'Heroes of Goo Jit Zu',NULL,1,'Australia',2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (121,'Hotel Del Luna',NULL,1,NULL,2019);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (122,'In the Cut','Jane Campion',2,'United Kingdom, Australia, France, United States',2003);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (123,'Luv Kushh',NULL,1,NULL,2012);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (124,'Pororo - The Little Penguin',NULL,1,'South Korea',2013);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (125,'Q-Force',NULL,1,'United States',2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (126,'Shikara','Vidhu Vinod Chopra',2,'India',2020);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (127,'A Cinderella Story','Mark Rosman',2,'United States, Canada',2004);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (128,'Agatha Christie''s Crooked House','Gilles Paquet-Brenner',2,NULL,2017);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (129,'An Unfinished Life','Lasse Hallström',2,'Germany, United States',2005);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (130,'Barbie Big City Big Dreams','Scott Pleydell-Pearce',2,NULL,2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (131,'Blade Runner: The Final Cut','Ridley Scott',2,'United States',1982);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (132,'Brave Animated Series',NULL,1,NULL,2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (133,'Chappie','Neill Blomkamp',2,'South Africa, United States',2015);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (134,'Clear and Present Danger','Phillip Noyce',2,'United States, Mexico',1994);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (135,'Cliffhanger','Renny Harlin',2,'United States, Italy, France, Japan',1993);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (136,'Cold Mountain','Anthony Minghella',2,'United States, Italy, Romania, United Kingdom',2003);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (137,'Crocodile Dundee in Los Angeles','Simon Wincer',2,'Australia, United States',2001);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (138,'Dear John','Lasse Hallström',2,'United States',2010);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (139,'Do the Right Thing','Spike Lee',2,'United States',1989);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (140,'El patrón, radiografía de un crimen','Sebastián Schindel',2,'Argentina, Venezuela',2014);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (141,'Extraction','Steven C. Miller',2,'United States, United Kingdom, Canada',2015);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (142,'Freedom Writers','Richard LaGravenese',2,'Germany, United States',2007);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (143,'Green Lantern','Martin Campbell',2,'United States',2011);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (144,'House Party','Reginald Hudlin',2,'United States',1990);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (145,'House Party 2','George Jackson, Doug McHenry',2,'United States',1991);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (146,'House Party 3','Eric Meza',2,'United States',1994);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (147,'How to Be a Cowboy',NULL,1,NULL,2021);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (148,'HQ Barbers','Gerhard Mostert',1,NULL,2020);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (149,'I Got the Hook Up','Michael Martin',2,'United States',1998);
INSERT INTO `movies`.`movies` (`id`,`title`,`director`,`type_id`,`countries`,`release_year`) VALUES (150,'In Too Deep','Michael Rymer',2,'United States',1999);
COMMIT;
