# Generated by Django 5.0.4 on 2024-05-01 01:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField(unique=True)),
                ('year', models.IntegerField(default=0)),
                ('pages', models.IntegerField(default=0)),
                ('description', models.TextField(default='None')),
                ('genres', models.TextField(default='None')),
                ('authors', models.TextField(default='Jane Doe')),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('rating_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('average_rating', models.FloatField(default=0)),
                ('ratings_count', models.IntegerField(default=0)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='BookRec.books')),
            ],
        ),
    ]
