# Generated by Django 5.0.4 on 2024-05-01 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookRec', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratings',
            old_name='book_id',
            new_name='book',
        ),
    ]
